# Tensor

## Import Tensorflow

In [5]:
import tensorflow as tf

## 0D-Tensor
- auch Skalar genannt

In [6]:
my_scalar = tf.constant(1, name="mein Skalar")

### Ausgabe des Skalars
- Zeigt nur die Daten innerhalb des 0D-Tensor an

In [7]:
tf.print(my_scalar)

1


#### mehr Daten über Skalar
- Zeigt relevante Informationen zum Tensor an

In [8]:
print(my_scalar)

tf.Tensor(1, shape=(), dtype=int32)


## 1D Tensor
- kann Einzelwertreihenfolgen speichern

In [9]:
tensor_1d = tf.constant([1,2,3,4])
print(tensor_1d)
tensor_1d_with_strings = tf.constant(["Hallo", "Welt", "dies", "ist", "ein 1D-Tensor!"])
print(tensor_1d_with_strings)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([b'Hallo' b'Welt' b'dies' b'ist' b'ein 1D-Tensor!'], shape=(5,), dtype=string)


### Alternative Aufgabe

In [10]:
tf.print(tensor_1d)
tf.print(tensor_1d_with_strings)

[1 2 3 4]
["Hallo" "Welt" "dies" "ist" "ein 1D-Tensor!"]


## 2D Tensor
- auch Matrix genannt
- kann indizierte (mehrspaltige) Einträge speichern

In [11]:
tensor_2d = tf.constant([[1, 2], [3, 4], [5, 6]])
print(tensor_2d)
tensor_2d_with_strings = tf.constant([["Petra", "Schmitt"], ["Max", "Mustermann"], ["John", "Doe"]])
print(tensor_2d_with_strings)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[b'Petra' b'Schmitt']
 [b'Max' b'Mustermann']
 [b'John' b'Doe']], shape=(3, 2), dtype=string)


### Alternative Ausgabe

In [12]:
tf.print(tensor_2d)
tf.print(tensor_2d_with_strings)

[[1 2]
 [3 4]
 [5 6]]
[["Petra" "Schmitt"]
 ["Max" "Mustermann"]
 ["John" "Doe"]]


## 3D-Tensor

In [13]:
tensor_3d = tf.constant([
    [[1,4], [3,8]],
    [[5,7], [9,3]]
])
tf.print(tf.rank(tensor_3d)) #  tf.rank gibt die Ordnung des Tensors wieder(1, 2, 3 oder 4D Tensor)

3


## 4D-Tensor
- z.B. ein Video
- Reihenfolge von Bildern (3D-Tensor)

## Numpy Strukturen in Tensorflow

In [19]:
import numpy as np

np_array = np.arange(0, 5, step=0.5)
tensor_from_numpy = tf.constant(np_array, name="converted")
print("Eine Numpy-Struktur kann in einen Tensor umgewandelt werden:", tensor_from_numpy)

print("und wieder zurück in eine NumPy-Struktur:", tensor_from_numpy.numpy())

Eine Numpy-Struktur kann in einen Tensor umgewandelt werden: tf.Tensor([0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5], shape=(10,), dtype=float64)
und wieder zurück in eine NumPy-Struktur: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
